sonar.projectKey=farid-alfernass_forgebe
sonar.organization=farid-alfernass
sonar.projectName=forgebe

sonar.sources=cmd,internal
sonar.tests=internal
sonar.test.inclusions=**/*_test.go
sonar.exclusions=**/testdata/**,**/*.md,**/bin/**,**/vendor/**

sonar.go.coverage.reportPaths=coverage.out
sonar.sourceEncoding=UTF-8
